const cp=require('node:child_process');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const php='C:/xampp/php/php.exe';const base='http://localhost/nutrifittwo/backend/api';
const pre="date_default_timezone_set('America/Argentina/Buenos_Aires');require 'backend/config/database.php';$db=(new Database())->getConnection();";
function db(code){const r=cp.spawnSync(php,['-r',pre+code],{cwd:root,encoding:'utf8'});if(r.status)throw Error(r.stderr);return r.stdout.trim();}
let count=0;function check(label,ok){assert.ok(ok,label);console.log('PASS '+label);count++;}
const users=[];
async function req(u,ep,b){const r=await fetch(base+ep,{method:'POST',headers:{'Content-Type':'application/json',...(u?.cookie?{Cookie:u.cookie}:{})},body:JSON.stringify(b)});if(u&&r.headers.getSetCookie().length)u.cookie=r.headers.getSetCookie().at(-1).split(';')[0];return r;}
async function json(u,ep,b){const r=await req(u,ep,b);return {status:r.status,j:await r.json()};}
async function user(name,onboard=true){const u={email:'nf-qr-'+Date.now()+'-'+users.length+'@example.invalid',password:'NutriFit-qr-2026!',name};const r=await json(u,'/auth/registro.php',{nombre:name,email:u.email,password:u.password});check('registro temporal',r.j.success);u.id=r.j.data.id;users.push(u);if(onboard){const r=await json(u,'/auth/onboarding.php',{edad:30,genero:'masculino',peso_actual:70,altura:170,objetivo:'mantener_peso',nivel_actividad:'moderado',lugar_entreno:'casa',tipo_dieta:'omnivora',alergias:['ninguna']});check('onboarding temporal',r.j.success);}return u;}
async function routine(u){const r=await fetch(base+'/entrenamiento/rutina_recomendada.php',{headers:{Cookie:u.cookie}});return (await r.json()).data;}
async function main(){try{
const a=await user('José Núñez & <Ana>');const b=await user('=HYPERLINK("test")');const empty=await user('Cuenta vacía',false);
const original=await routine(a);const rid=Number(original.id);const serial=()=>db('echo json_encode($db->query("SELECT titulo,lugar,nivel_dificultad FROM rutinas_ejercicios WHERE id='+rid+'")->fetch());echo json_encode($db->query("SELECT nombre,series,repeticiones,descanso_segundos FROM ejercicios WHERE rutina_id='+rid+' ORDER BY orden")->fetchAll());');const before=serial();
const uid=a.id;db('$db->exec("INSERT INTO progreso_peso(usuario_id,peso_registrado,fecha) VALUES('+uid+',71,DATE_SUB(CURDATE(),INTERVAL 29 DAY)),('+uid+',70,DATE_SUB(CURDATE(),INTERVAL 6 DAY)),('+uid+',69,CURDATE()) ON DUPLICATE KEY UPDATE peso_registrado=VALUES(peso_registrado)");$db->exec("INSERT INTO registros_hidratacion(usuario_id,fecha,vasos) VALUES('+uid+',CURDATE(),8)");$db->exec("INSERT INTO registros_pasos(usuario_id,fecha,pasos) VALUES('+uid+',CURDATE(),4321)");$db->exec("INSERT INTO registros_actividad(usuario_id,tipo_actividad_id,fecha,duracion_segundos,pasos,distancia_metros) SELECT '+uid+',id,CURDATE(),1800,3000,2000 FROM tipos_actividad WHERE clave=\'caminata\'");$db->exec("INSERT INTO registros_entrenamiento(usuario_id,rutina_id,fecha,xp_ganado) VALUES('+uid+','+rid+',CURDATE(),0)");$db->exec("INSERT INTO registros_comidas(usuario_id,alimento_id,tipo_comida,gramos,calorias_totales,proteinas_totales,fecha) SELECT '+uid+',id,\'almuerzo\',100,123,11,CURDATE() FROM alimentos WHERE fuente=\'local\' LIMIT 1");');
for(const period of ['7','30','todo']){const r=await req(a,'/progreso/exportar.php',{periodo:period,formato:'pdf'});const bytes=Buffer.from(await r.arrayBuffer());check('PDF '+period+' binario real',r.status===200&&bytes.subarray(0,5).toString()==='%PDF-');check('PDF privado bajo demanda '+period,r.headers.get('cache-control').includes('no-store')&&r.headers.get('content-disposition').includes('attachment'));fs.writeFileSync(root+'/tests/progreso-'+period+'.pdf',bytes);}
let r=await req(empty,'/progreso/exportar.php',{periodo:'todo',formato:'pdf'});check('PDF vacío',r.status===200&&Buffer.from(await r.arrayBuffer()).subarray(0,5).toString()==='%PDF-');
check('exportación sin sesión 401',(await req(null,'/progreso/exportar.php',{periodo:'7',formato:'pdf'})).status===401);
check('manipular user_id rechazado',(await req(b,'/progreso/exportar.php',{periodo:'7',formato:'pdf',user_id:a.id})).status===422);
check('período inválido rechazado',(await req(a,'/progreso/exportar.php',{periodo:'999',formato:'pdf'})).status===422);
r=await req(b,'/progreso/exportar.php',{periodo:'todo',formato:'csv'});const csv=Buffer.from(await r.arrayBuffer());check('CSV UTF8 con protección fórmula',csv.subarray(0,3).equals(Buffer.from([239,187,191]))&&csv.toString().includes("'=HYPERLINK"));
let q=await json(a,'/entrenamiento/compartir_rutina.php',{accion:'compartir',rutina_id:rid});check('token seguro',q.j.success&&/^NF-RUTINA-1:[a-f0-9]{64}$/.test(q.j.data.codigo));const code=q.j.data.codigo;
q=await json(b,'/entrenamiento/compartir_rutina.php',{accion:'preview',codigo:code});check('preview correcto sin privados',q.j.success&&q.j.data.rutina.titulo===original.titulo&&q.j.data.rutina.ejercicios.length===original.ejercicios.length&&!JSON.stringify(q.j.data).includes(a.email)&&!('usuario_id' in q.j.data.rutina)&&!('objetivo' in q.j.data.rutina));
check('preview no importa',db('echo $db->query("SELECT COUNT(*) FROM rutina_importaciones WHERE usuario_id='+b.id+'")->fetchColumn();')==='0');
const xpBefore=db('echo $db->query("SELECT xp_total FROM usuarios WHERE id='+b.id+'")->fetchColumn();');
q=await json(b,'/entrenamiento/compartir_rutina.php',{accion:'importar',codigo:code});const imported=q.j.data.rutina_id;check('copia de B',q.j.success&&imported!==rid&&!q.j.data.ya_importada);check('A intacta',serial()===before);check('importación no otorga XP',db('echo $db->query("SELECT xp_total FROM usuarios WHERE id='+b.id+'")->fetchColumn();')===xpBefore);
q=await json(b,'/entrenamiento/compartir_rutina.php',{accion:'importar',codigo:code});check('doble importación idempotente',q.j.data.ya_importada&&q.j.data.rutina_id===imported);
q=await json(b,'/entrenamiento/compartir_rutina.php',{accion:'seleccionar',rutina_id:imported});check('selección de copia',q.j.success);const active=await routine(b);check('persistencia y ejercicios nuevos',Number(active.id)===imported&&active.importada&&Number(active.ejercicios[0].id)!==Number(original.ejercicios[0].id));
q=await json(b,'/entrenamiento/compartir_rutina.php',{accion:'compartir',rutina_id:rid});check('IDOR compartir rechazado',q.status===404);
q=await json(b,'/entrenamiento/compartir_rutina.php',{accion:'seleccionar',rutina_id:rid});check('IDOR selección rechazado',q.status===404);
q=await json(b,'/entrenamiento/compartir_rutina.php',{accion:'revocar',rutina_id:rid});check('IDOR revocar rechazado',q.status===404);
q=await json(b,'/entrenamiento/compartir_rutina.php',{accion:'preview',codigo:'NF-RUTINA-1:'+'f'.repeat(64)});check('token desconocido rechazado',q.status===404);
q=await json(b,'/entrenamiento/compartir_rutina.php',{accion:'preview',codigo:'<script>bad</script>'});check('token manipulado rechazado',q.status===404);
q=await json(a,'/entrenamiento/compartir_rutina.php',{accion:'revocar',rutina_id:rid});check('revocación propia',q.j.success);q=await json(b,'/entrenamiento/compartir_rutina.php',{accion:'preview',codigo:code});check('revocado rechazado',q.status===404);
q=await json(a,'/entrenamiento/compartir_rutina.php',{accion:'compartir',rutina_id:rid});const expired=q.j.data.codigo;db('$db->exec("UPDATE rutina_comparticiones SET expira_en=DATE_SUB(NOW(),INTERVAL 1 SECOND) WHERE usuario_id='+a.id+' AND revocada_en IS NULL");');q=await json(b,'/entrenamiento/compartir_rutina.php',{accion:'importar',codigo:expired});check('vencido rechazado',q.status===404);
q=await json(b,'/entrenamiento/compartir_rutina.php',{accion:'seleccionar',rutina_id:0});check('volver al plan personalizado',q.j.success&&Number((await routine(b)).id)!==imported);
check('QR sin sesión 401',(await req(null,'/entrenamiento/compartir_rutina.php',{accion:'listar'})).status===401);
console.log('TOTAL '+count+' passed');if(process.argv.includes('--ui'))console.log(JSON.stringify({a:{id:a.id,email:a.email,password:a.password},b:{id:b.id,email:b.email,password:b.password}}));
}finally{if(!process.argv.includes('--ui'))for(const u of users)db('$db->beginTransaction();$db->exec("DELETE FROM registros_entrenamiento WHERE usuario_id='+u.id+'");$db->exec("DELETE FROM ejercicios_completados WHERE usuario_id='+u.id+'");$db->exec("DELETE FROM rutinas_ejercicios WHERE usuario_id='+u.id+'");$db->exec("DELETE FROM usuarios WHERE id='+u.id+'");$db->commit();');}}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
