const fs=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../frontend/js/app.js'),'utf8');
class Element {constructor(){this.children=[];this.classList={values:new Set(),add(x){this.values.add(x)},remove(x){this.values.delete(x)}};}append(...x){this.children.push(...x)}appendChild(x){this.children.push(x)}replaceChildren(){this.children=[]}setAttribute(){}get textContent(){return (this._text||'')+this.children.map(x=>x.textContent).join('')}set textContent(v){this._text=v}}
const toast=new Element();const timers=new Map();let clock=0;let state;
const context={document:{getElementById:id=>id==='toast'?toast:null,createElement:()=>new Element(),querySelector:()=>null,querySelectorAll:()=>[]},window:{NutriFitUser:{}},renderUserChip:s=>{state=s},robotAvatarPerfil:null,robotAvatarModal:null,marcoClaseDeNombre:()=>'',auraClaseDeNombre:()=>'',setTimeout:fn=>{timers.set(++clock,fn);return clock},clearTimeout:id=>timers.delete(id),launchConfetti:()=>{},reaccionarRobotAvatar:()=>{}};
vm.createContext(context);vm.runInContext(source.slice(source.indexOf('const colaNotificaciones'),source.indexOf('function launchConfetti')),context);
const g={estado:{id:1,nivel:2,nutri_coins:100},logros_nuevos:[{clave:'primera_comida',titulo:'<img onerror=bad>',xp:{xp_ganado:22}}],retos_nuevos:[{clave:'sem_racha',periodo:'2026-W41',titulo:'Sin parar',xp:{xp_ganado:77}}],xp_otorgado:110,subio_de_nivel:false,logros:[],retos:{retos:[]}};
context.handleGamificationResponse(g,{xp_ganado:11});assert.match(toast.textContent,/Logro desbloqueado/);assert.match(toast.textContent,/<img onerror=bad>/);assert.equal(toast.children.length,2);assert.equal(state.nivel,2);
context.handleGamificationResponse(g,{xp_ganado:11});context.cerrarNotificacion();assert.match(toast.textContent,/Reto completado/);assert.match(toast.textContent,/77 XP/);context.cerrarNotificacion();assert.equal(toast.textContent,'');assert.equal(timers.size,0);
context.showToast('Compra exitosa');context.showToast('Objeto equipado');assert.equal(toast.textContent,'Compra exitosa×');[...timers.values()][0]();assert.equal(toast.textContent,'Objeto equipado×');[...timers.values()][0]();assert.equal(toast.textContent,'');assert.equal(toast.classList.values.has('show'),false);
console.log('PASS cola, deduplicación, texto seguro, estado backend y cierre automático');
